import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import { FooterComponent } from '@/components/footer'
import { NavbarUser } from '@/components/navbar/navbarUser'

const dm_Sans = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dm_Sans.className}>
        {children}
        <FooterComponent />
      </body>
    </html>
  )
}
