'use client'

import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'
import { FooterComponent } from '@/components/footer'
import { NavbarUser } from '@/components/navbar/navbarUser'
import { NavbarDefault } from '@/components/navbar/navbarComponent'
import { usePathname } from 'next/navigation'

const dm_Sans = DM_Sans({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const path = usePathname().split('/')[1]

  return (
    <html lang="en">
      <body className={dm_Sans.className}>
        {path !== String('register') && path !== String('login') && (
          <NavbarDefault />
        )}

        {children}
        <FooterComponent />
      </body>
    </html>
  )
}
